include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  errors:
    always_use_package_imports: ignore
    avoid_dynamic_calls: ignore
    prefer_relative_imports: error
    parameter_assignments: error
    dead_code: error
    close_sinks: error
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/generated/**"
    - "**/generated_plugin_registrant.dart"
    - "**.mocks.dart"

linter:
  rules:
    sort_pub_dependencies: false
