name: gallery_app
description: Gallery App

publish_to: 'none'

version: 1.0.4+6

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^5.0.4
  basic_utils: ^5.7.0
  battery_plus: ^4.0.2
  build_context: ^3.0.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.0
  package_info_plus: ^4.0.1
  path_provider: ^2.0.14
  permission_handler: ^11.0.1
  responsive_framework: ^0.1.7
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.12
  transparent_image: ^2.0.1
  flutter_device_type: ^0.4.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.1.14
  file_picker: ^5.3.2
  internet_connection_checker: ^1.0.0+1
  photo_view: ^0.14.0
  drag_down_to_pop: ^1.0.0





dev_dependencies:
  assets_gen: ^1.2.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.6
  diff_match_patch: ^0.4.1
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  lint: ^1.5.3
  mockito: ^5.0.17
  pretty_dio_logger: ^1.3.1
  retrofit_generator: null
  state_notifier_test: ^0.0.5

dependency_overrides:
  intl: ^0.18.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_intl:
  enabled: true
